todo/urls.py
from django.urls import path
from .views import TaskListView, TaskCreateView, TaskDetailView, TaskUpdateView

app_name="todo"

urlpatterns = [
    path('', TaskListView.as_view(), name = 'task_list'),
    path('create_task/', TaskCreateView.as_view(), name = 'task_create'),
    path('task_detail/<int:pk>/', TaskDetailView.as_view(), name= 'task_detail'),
    path('task_update/<int:pk>/', TaskUpdateView.as_view(), name = "task_update")
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls'), name='todo')
]

todo/models.py
from sqlite3 import Row
from tkinter import Widget
from django.db import models
from datetime import date

# Create your views here.
class Task(models.Model):
    title = models.CharField(max_length=50)
    due_date = models.DateField()
    date_stamp = date.today().strftime("%B %d, %Y")
    description = models.TextField(blank=True)
    complete = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title} due {self.due_date}"

todo/views.py
from asyncio import Task
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from todo.models import Task

class TaskListView(ListView):
    model = Task
    queryset = Task.objects.order_by('due_date')
    context_object_name = "task_list"

class TaskCreateView(CreateView):
    model = Task
    fields = ["title","due_date","description"]
    success_url = reverse_lazy('todo:task_list')

class TaskDetailView(DetailView):
    model = Task

class TaskUpdateView(UpdateView):
    model = Task
    fields = ["complete"]
    success_url = reverse_lazy('todo:task_list')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <title>Todo List</title>
</head>
<body>
    <!--Navbar-->
    
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="{% url 'todo:task_list' %}">Task</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                    <a class="nav-link" href="{% url 'todo:task_create' %}">Add Task <span class="sr-only"></span></a>
                    </li>
                </ul>
            </div>
        </nav>
    

    {% block content %}
    {% endblock %}

    
</body>
</html>

todo/templates/todo/task_detail.html
{% extends 'base.html' %}

{% block content %}
<div class = "container">
    <h1 class = "display-1">{{task.title}}</h1>
    <strong>Status: {{ task.complete|yesno:"Done,Todo" }}</strong>
    <p>Due Date: {{task.due_date}}</p>
    <p>Date Created: {{task.date_stamp}}</p>
    <p>Description: {{task.description}}</p>
    
    <form action="{% url 'todo:task_update' task.id  %}">
        {% csrf_token%}

        <button class="btn btn-success">Complete</button>
    </form>

</div>
{% endblock %}

todo/templates/todo/task_form.html
{% extends 'base.html' %}
    {% block content %}
    <div class = "container">
            <h1>Task</h1>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <input type="submit" value="Submit">
            </form>
        </div>
    {% endblock content %}

todo/templates/todo/task_list.html
{% extends 'base.html' %}

{% block content%}
    
    <div class="container">
        <h1>Task </h1>
        <ul>
            {% for task in task_list %}
                <li>
                    {% if task.complete == True %}
                    <a href="/todo/task_detail/{{task.id}}" class="btn btn-success" role="button">{{task}}</a>
                    {% else %}
                    <a href="/todo/task_detail/{{task.id}}" class="btn btn-secondary" role="button">{{task}}</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    </div>

{% endblock %}